spring.application.name=demo
server.port=9090
openai.api.key=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